# Generated by Django 4.1 on 2022-09-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='reciever_user',
            new_name='receiver_user',
        ),
    ]
