# Generated by Django 4.1 on 2022-09-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_reciever_user_messagemodel_receiver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
