# Generated by Django 4.1 on 2022-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_messagemodel_body_alter_messagemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
